server:
  port: 9001

spring:
  profiles:
    active: prod
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/treinamento
    username: marcos
    password: teste

app:
  logging:
    host: 192.168.6.182:5000
